version: '3.6'

services:
  app:
    build:
      context: .
      args:
        app_path: /desafio-dev
    container_name: desafio-dev
    env_file: .env
    volumes:
      - .:/desafio-dev
    ports:
      - "3000:3000"
    command: "bundle exec puma -C config/puma.rb"
    depends_on:
      - postgres
    networks:
      - desafio-dev-net
  
  sidekiq:
    build:
      context: .
      args:
        app_path: /desafio-dev
    env_file: .env
    container_name: desafio-dev-sidekiq
    volumes:
      - .:/desafio-dev
    depends_on:
      - redis
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    networks:
      - desafio-dev-net

  redis:
    image: redis
    container_name: desafio-dev-redis
    ports:
      - "6379"
    networks:
      - desafio-dev-net

  postgres:
    image: postgres:9.3
    container_name: desafio-dev-db
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker-volumes/desafio-dev/db/:/var/lib/postgresql/data
    networks:
      - desafio-dev-net

networks:
  desafio-dev-net:
    driver: bridge
    name: desafio-dev-net